services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: cardtransactions-sql
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Richard@123!"
      MSSQL_PID: Developer
    ports:
      - "1434:1433"
    healthcheck:
      test: /opt/mssql-tools18/bin/sqlcmd -C -S localhost -U sa -P "Richard@123!" -Q "SELECT 1" || exit 1
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s