<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\CardTransactions.Contracts\CardTransactions.Contracts.csproj" />
    <ProjectReference Include="..\CardTransactions.Data\CardTransactions.Data.csproj" />
  </ItemGroup>

</Project>
